### PR TITLE
Update jdk8 installers for Jan 2024 release

### PR DESCRIPTION
**Pull request by Haroon-Khel**
Once arm32 is out this can be merged

### CODE REVIEW

**Review by sxa — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel ci failures due to aarch32 I think ?

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
Seeing an error in the changelog

```
/var/tmp/rpm-tmp.25nVAQ: line 38: cd: jdk8u392-b08-aarch32-20231020-jre: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.25nVAQ (%prep)
    bogus date in %changelog: Thu Oct 25 2023 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.392.0.0.8-1
    Bad exit status from /var/tmp/rpm-tmp.25nVAQ (%prep)
```

**Comment by jiekang** [comment]
> Seeing an error in the changelog
> 
> ```
> /var/tmp/rpm-tmp.25nVAQ: line 38: cd: jdk8u392-b08-aarch32-20231020-jre: No such file or directory
> error: Bad exit status from /var/tmp/rpm-tmp.25nVAQ (%prep)
>     bogus date in %changelog: Thu Oct 25 2023 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.392.0.0.8-1
>     Bad exit status from /var/tmp/rpm-tmp.25nVAQ (%prep)
> ```

Oct 25 is a Wednesday :P

**Comment by Haroon-Khel** [comment]
> Oct 25 2023 is a Wednesday :P

Surprised it picked up on that. Thanks Jie

**Comment by Haroon-Khel** [comment]
That fixed it

**Pull request merged**
