### PR TITLE
JULY CPU - JDK21 & JDK22 & JDK17 Updates For Shipping Linux Packages

### PR DESCRIPTION
**Pull request by steelhead31**
Updates required for JDK21 & JDK22 Alpine, Debian, RH & SUSE packages.

Also includes a bump for JDK17 / JRE17 to bump the spec version for some missing signatures.

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

**Review by sxa — COMMENTED** [review]
Tricky to review every part of this in detail but I expect it's ok and we can correct if something goes wrong.
One comment though - are [the changes to build.sh](https://github.com/adoptium/installer/pull/964/files#diff-e6b9dd1bc6d6f4e60e402932a3306783e062cc8683f364a7fc94bf238cacbab9) supposed to be in this PR? If so probably worth adding a comment into this PR mentioning it since it looks like a change in functionality.

**Comment by steelhead31** [comment]
> Tricky to review every part of this in detail but I expect it's ok and we can correct if something goes wrong. One comment though - are [the changes to build.sh](https://github.com/adoptium/installer/pull/964/files#diff-e6b9dd1bc6d6f4e60e402932a3306783e062cc8683f364a7fc94bf238cacbab9) supposed to be in this PR? If so probably worth adding a comment into this PR mentioning it since it looks like a change in functionality.

Yes, I think this has already been merged, so actually went in with the changes for JDK8/11 as they were having the issues. , as per #961

**Comment by steelhead31** [comment]
Added a commit to allow a new push of JDK/JRE17 due to the issues with GPG signing yesterday, and a need to republish corrected binaries. ( raised in issue #962 ), but not present in every RPM based distribution.

**Review by sxa — APPROVED** [review]

**Pull request merged**
