### PR TITLE
Installer updates for JDK8 for July 2023 release

### PR DESCRIPTION
**Pull request by adamfarley**
Styled after the changes in [April](https://github.com/adoptium/installer/pull/518/files).

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by jiekang** [comment]
JDK 8 Red Hat relevant logs:

```
Download failed:
404 Client Error: Not Found for url: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u382-b05/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz
Downloading: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u382-b05/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz.sha256.txt
Download failed:
404 Client Error: Not Found for url: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u382-b05/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz.sha256.txt
warning: bogus date in %changelog: Mon Apr 26 2023 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.372.0.0.7-1.adopt0
setting SOURCE_DATE_EPOCH=1690243200
warning: bogus date in %changelog: Thu Aug 08 2022 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.345.0.0.1.adopt0
error: Bad file: /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz.sha256.txt: No such file or directory
error: Bad file: /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz: No such file or directory
    bogus date in %changelog: Mon Apr 26 2023 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.372.0.0.7-1.adopt0
    bogus date in %changelog: Thu Aug 08 2022 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.345.0.0.1.adopt0
    Bad file: /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz.sha256.txt: No such file or directory
    Bad file: /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_arm_linux_hotspot_8u382b05.tar.gz: No such file or directory
```

**Comment by adamfarley** [comment]
Thanks Jie. I think the issues were resolved successfully, however we do still have a failure or two which are all due to Arm32 not being released yet.

**Comment by adamfarley** [comment]
Ok, something's gone wrong here. Will fix.

**Comment by karianna** [comment]
Hmm, has the underlying Alpine host we test on changed?  Perhaps a newer version?  Your change seems benign

**Comment by gdams** [comment]
So this is to do with the fact that alpine 3.18 no longer has a `libxp-dev` package.

See 3.18:

```output
/ # apk search libxp
libxpm-3.5.16-r1
libxpm-dev-3.5.16-r1
libxpm-doc-3.5.16-r1
libxpresent-1.0.1-r1
libxpresent-dev-1.0.1-r1
libxpresent-doc-1.0.1-r1
```

vs 3.17

```output
/ # apk search libxp
libxpm-3.5.16-r1
libxpm-dev-3.5.16-r1
libxpm-doc-3.5.16-r1
libxpresent-1.0.1-r1
libxpresent-dev-1.0.1-r1
libxpresent-doc-1.0.1-r1
```

**Comment by gdams** [comment]
Looking at the community image they recently removed the missing dependency so I'm going to give it a go here (https://github.com/alpinelinux/aports/commit/681bad724d0311f9384a32b89b7612923c26e229)

**Comment by gdams** [comment]
@adamfarley where are the JRE changes for deb/RPM?

**Comment by adamfarley** [comment]
@gdams - Good spot. Fixed.

**Comment by gdams** [comment]
> @gdams - Good spot. Fixed.

@adamfarley you've removed my fixes

**Comment by adamfarley** [comment]
Another good spot by George. I've re-introduced the fix (the exclusion of libxp-dev from the APKBUILD files) and the tests on Alpine appear to pass now.

Still a few failures, but they all look like arm-build-not-found errors, which should be solved once arm builds are released.

**Pull request merged**
