### PR TITLE
Updating Microsoft installer

### PR DESCRIPTION
**Pull request by joe-braley**
Updates Microsoft's JDK11 and JDK17 packages to reflect the latest release.

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by jmjaffe37** [comment]
@joe-braley, can you also add the changes to the debian dependencies to this PR?

**Comment by joe-braley** [comment]
> @joe-braley, can you also add the changes to the debian dependencies to this PR?

@jmjaffe37 I believe they have been approved [here](https://github.com/adoptium/installer/pull/693).

**Comment by jmjaffe37** [comment]
@joe-braley, oh I didn't see that. Thanks Joe!

**Review by gdams — APPROVED** [review]

**Pull request merged**
