### PR TITLE
 update: remove hardcoded jdk version

### PR DESCRIPTION
**Pull request by zdtsw**
to fix error like 
```
[WS-CLEANUP] done
[Pipeline] unstash
[Pipeline] sh
+ ./gradlew packageJdkDebian --parallel -PPRODUCT=temurin -PPRODUCT_VERSION=8 -PARCH=arm64

ERROR: JAVA_HOME is set to an invalid directory: /home/jenkins/tools/hudson.model.JDK/jdk-11.0.13_8/jdk-11.0.13+8

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

because of this block, the node assigned to build installer need to have 11.0.13+8 installed.
this is not the case, which caused many build failed with JAVA_HOME either not match or not set to that path.

if remove this, job will use default JAVA_HOME which the agent has to do the gradle

Dry-run (only build no upload): https://ci.adoptopenjdk.net/job/Sophia-adoptium-packages-linux-pipeline/196/console

### CODE REVIEW

**Comment by zdtsw** [comment]
saw in https://github.com/adoptium/installer/pull/356/commits/95dd0f2d1ec1024b9985d9e26303b2d7c9f856bc 
initial 
```
tools {
        jdk "JDK11"
    } 
```
was added. do we still need to specify jdk as tools? @gdams

**Review by steelhead31 — APPROVED** [review]
Looks good to me.

**Comment by gdams** [comment]
It depends if we can be sure that Java 11 is installed on all the machines we build the installed on (and available through the JAVA_HOME variable)

**Review by karianna — APPROVED** [review]

**Review by karianna — DISMISSED** [review]
Failing GH Actions.

**Review by smlambert — APPROVED** [review]

**Comment by zdtsw** [comment]
> Failing GH Actions.

cannot think this PR could cause the failiure, esp. GH action does not even use Jenkinsfile, and all seems failed for Deb.
re-run jdk8 on Deb just to see if it is env. issue.

**Comment by zdtsw** [comment]
> > Failing GH Actions.
> 
> cannot think this PR could cause the failiure, esp. GH action does not even use Jenkinsfile, and all seems failed for Deb. re-run jdk8 on Deb just to see if it is env. issue.



> > Failing GH Actions.
> 
> cannot think this PR could cause the failiure, esp. GH action does not even use Jenkinsfile, and all seems failed for Deb. re-run jdk8 on Deb just to see if it is env. issue.



> > Failing GH Actions.
> 
> cannot think this PR could cause the failiure, esp. GH action does not even use Jenkinsfile, and all seems failed for Deb. re-run jdk8 on Deb just to see if it is env. issue.

it went pass, running the rest, but should be good to go

**Pull request merged**
