### PR TITLE
add license to deb control files

### PR DESCRIPTION
**Pull request by gdams**
fixes: https://github.com/adoptium/installer/issues/381

### CODE REVIEW

**Comment by gdams** [comment]
This didn't seem to work. Paging @aahlenst incase he knows what I'm doing wrong here

**Comment by aahlenst** [comment]
Spec is on https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/. Mandatory fields seem to be missing like `Format`.

**Comment by sophia-guo** [comment]
I think the PR is good. Check the copyright I can see

```
dpkg-deb --fsys-tarfile temurin-8-jdk_8.0.312.0.0+7-1_amd64.deb |tar -xvO ./usr/share/doc/temurin-8-jdk/copyright
./usr/share/doc/temurin-8-jdk/copyright
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Files: *
Copyright: Oracle and/or its affiliates
License: GPL-2.0+CE
```

**Review by sophia-guo — APPROVED** [review]
LGTM

**Pull request merged**
