### PR TITLE
Update some metadata for Linux installer new

### PR DESCRIPTION
**Pull request by jerboaa**
We need to figure out which email address to use for RPM packages. Is this used in other installers?

### CODE REVIEW

**Comment by tellison** [comment]
> We need to figure out which email address to use for RPM packages. Is this used in other installers?

`temurin-dev@eclipse.org` ? unless it will be used for private notifications.

**Comment by jerboaa** [comment]
> > We need to figure out which email address to use for RPM packages. Is this used in other installers?
> 
> `temurin-dev@eclipse.org` ? unless it will be used for private notifications.

OK, works for me.

**Comment by jerboaa** [comment]
I'm not going to update the email in this PR since it clashes with #332 otherwise.

**Comment by karianna** [comment]
@jerboaa I think the PR I landed contains all of these fixes but you may want to rebase and check JIC

**Comment by jerboaa** [comment]
Yeah, no longer needed.

**Pull request closed without merging**
