### PR TITLE
removed ubuntu 22.10 support due to EoL

### PR DESCRIPTION
**Pull request by jmjaffe37**
This fixes the failures in the PR automated checks due to ubuntu 22.10's end of life

### CODE REVIEW

**Comment by jmjaffe37** [comment]
This GHA run (from my branch on my fork) shows that it fixes the problem outlined in the [issue 774](https://github.com/adoptium/installer/issues/744):

https://github.com/jmjaffe37/openjdk-installer/actions/runs/6332563576

**Review by karianna — APPROVED** [review]

**Review by gdams — APPROVED** [review]

**Comment by karianna** [comment]
https://github.com/adoptium/containers/issues/359 and https://github.com/adoptium/containers/issues/423 are related to this.  I think we need to start a policy doc on the website

**Comment by tellison** [comment]
Agreed, although I wasn't thinking of a _policy_ (this change is fine), rather the actual description of what is in/out of support for Temurin on Debian - [as we do with other OSes](https://adoptium.net/supported-platforms/).

**Comment by karianna** [comment]
Heh, had missed that, looks like we never stated we would support 22.10 (which isn't an LTS), I wonder if we mis stepped in adding it in the first place.

**Pull request merged**
