### PR TITLE
Ensure adoptium-ca-certificates deb file is archived

### PR DESCRIPTION
**Pull request by sxa**
The packaging job does not currently archive the `ca-certificates` `.deb` package. This PR resolves that.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by sxa** [comment]
Supercedes https://github.com/adoptium/installer/pull/372 which was merged prematurely

**Review by karianna — APPROVED** [review]
LGTM this time for real

**Comment by sxa** [comment]
I'm running [one more test](https://ci.adoptopenjdk.net/job/sxa-linuxnew-installer-deb/) after resolving the new merge conflict. Hopefully won't be a problem but I'm not trusting these changes any more today ;-)

**Comment by karianna** [comment]
> I'm running [one more test](https://ci.adoptopenjdk.net/job/sxa-linuxnew-installer-deb/) after resolving the new merge conflict. Hopefully won't be a problem but I'm not trusting these changes any more today ;-)

I'm letting you merge, #notmyfault ;-)

**Comment by sxa** [comment]
> I'm letting you merge, #notmyfault ;-)

Haha - you know that's my preference anyway ;-)

**Comment by sxa** [comment]
Temurin 8 redhat github check failed but I've seen intermittent failures on those, so I'm going to force a re-run of the checks.

**Comment by sxa** [comment]
> Temurin 8 redhat github check failed but I've seen intermittent failures on those, so I'm going to force a re-run of the checks.

Those failures (Also on 17 redhat) seem to be happening for other PRs so I'm not going to let that block merging of this, but they will need to be addressed - will raise as a separate issue.

**Pull request merged**
