### PR TITLE
Unify "buildCli" method/vars (#430)

### PR DESCRIPTION
**Pull request by ascheman**
This PR is subject to some (private Jenkins) testing before finally raised.

### CODE REVIEW

**Comment by ascheman** [comment]
This fix seems to work better than #604, I suggest to close it and to approve this one instead, @zdtsw / @steelhead31 / @andrew-m-leonard

**Review by zdtsw — APPROVED** [review]

**Review by steelhead31 — APPROVED** [review]
I've tested these changes in dry runs of the installer builder, and following a few fixes on the dockerhosts to update out of date docker images, can confirm they are now working as per [https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/206/](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/206/) & https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/207/

**Comment by karianna** [comment]
@ascheman Did you mean to close this PR or merge it?

**Comment by ascheman** [comment]
Looks like it was (manually?) merged by @steelhead31?

image

He asked me to rebase my branch in the course of the parallel testing on Jenkins (cf. Slack). But when I rebased, it was already merged. When pushing the rebased state to GH, the branch was closed, seemingly by me (though I didn't do this actively).

image

The only thing I did on GH then, was deleting my branch:

image

**Pull request closed without merging**
