### PR TITLE
Adding "application/x-java-jnlp-file" mimetype association to MSI

### PR DESCRIPTION
**Pull request by psoujany**
This PR is backport of https://github.com/AdoptOpenJDK/IcedTea-Web/pull/384

Signed-off-by: Pasam Soujanya psoujany@in.ibm.com

### CODE REVIEW

**Comment by karianna** [comment]
On PMC agenda

**Review by gdams — APPROVED** [review]
Don't think there's the need for this to be on the PMC agenda @karianna (for starters Eclipse Temurin doesn't bundle ITW so this code doesn't affect us)

Approving on the basis that this is wrapped in the correct conditional to only modify the installers if ITW is being bundled

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
