### PR TITLE
fix: path in artifactory for oraclelinux

### PR DESCRIPTION
**Pull request by zdtsw**
Ref: https://github.com/adoptium/installer/issues/582

### CODE REVIEW

**Comment by gdams** [comment]
Noting that this is a breaking change, probably needs the PMC to talk through this one

**Comment by zdtsw** [comment]
> Noting that this is a breaking change, probably needs the PMC to talk through this one

convert to "draft" till PMC's decision on #582

**Comment by zdtsw** [comment]
any conclusion for this ?

**Comment by karianna** [comment]
Added to agenda for next meeting

**Comment by smlambert** [comment]
PMC call March 8th, since this PR would break people, suggest to not go this route / close PR.

Preferred approach is to update the documentation that is not correct (as reported in https://github.com/adoptium/installer/issues/582).

**Comment by zdtsw** [comment]
close PR as it is not needed

**Pull request closed without merging**
