### PR TITLE
Replaced msi properties which are evaluated at runtime with variables that are evaluated at build time. 

### PR DESCRIPTION
**Pull request by adipiciu**
Fixes issue #741

### CODE REVIEW

**Comment by karianna** [comment]
@adipiciu Are you able to sign the Eclipse CLA please :-)

**Comment by adipiciu** [comment]
> Are you able to sign the Eclipse CLA please :-)

I signed the ECA, but I have a private email address on github and I can't link that to eclipse. How do you link private email?

**Comment by karianna** [comment]
Can you resign the commits? e.g. https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

**Comment by adipiciu** [comment]
> Can you resign the commits? e.g. https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

done

**Review by karianna — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
thanks @adipiciu !

**Pull request merged**
