### PR TITLE
Updated linux files for microsoft's jan 2024 psu

### PR DESCRIPTION
**Pull request by jmjaffe37**

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by karianna** [comment]
@jmjaffe37 GH Action checks seem to be failing...

**Comment by jmjaffe37** [comment]
@karianna, this is expected since our new version is not live yet. Once it is, the links used to download and test our installers will be up and running. At that point, I will mark this PR as "ready for review" and hopefully another GHA check will run.

**Comment by jmjaffe37** [comment]
Is someone able to set the GHA checks to rerun?
@karianna @gdams

**Comment by jmjaffe37** [comment]
@karianna I think you still have to add your approval before this merges successfully 😅

**Review by karianna — APPROVED** [review]

**Pull request merged**
