### PR TITLE
Update jdk8 installers to jdk8u342-07

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Re-running checks now all versions are available.

**Comment by sophia-guo** [comment]
JDK8 redhat and suse job failed with 

```
sha256sum -c /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u342b07.tar.gz.sha256.txt
sha256sum: target/linux/ppc64le/temurin/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u342b07.tar.gz: No such file or directory
```

The reason is the ppc64le sha file is incorrect , the extra folder information is unnecessary :

```
bc943c3e6bc1232ea4e7dd114831b609d83a79f271907941a18f1d7206f741b2  target/linux/ppc64le/temurin/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u342b07.tar.gz
```

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2202/artifact/target/linux/ppc64le/temurin/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u342b07.tar.gz.sha256.txt

**Comment by sxa** [comment]
> JDK8 redhat and suse job failed with
> 
> ```
> sha256sum -c /home/builder/rpmbuild/SOURCES/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u342b07.tar.gz.sha256.txt
> sha256sum: target/linux/ppc64le/temurin/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u342b07.tar.gz: No such file or directory
> ```

Existing issue: https://github.com/adoptium/temurin-build/issues/2865

**Comment by gdams** [comment]
Closing as https://github.com/adoptium/installer/pull/518 was merged instead

**Pull request closed without merging**
