### PR TITLE
fix: alpine build with less permission to copy file by user "builder"

### PR DESCRIPTION
**Pull request by zdtsw**
use doas to set root permission 
also download pub key from jenkins server due to abuild tests failure

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by zdtsw** [comment]
run in the test job (no upload enabled): https://ci.adoptopenjdk.net/job/Sophia-adoptium-packages-linux-pipeline/195/console

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by andrew-m-leonard — APPROVED** [review]

**Pull request merged**
