### PR TITLE
Remove s390x, arm32 for jdk21 debian from jenkins job if arch=all

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by sxa** [comment]
I'm a little reluctant to approve this given s390x will be good for the next release, and hopefully we can look at pushing arm32 forward.
Since we're able to complete this for the 21.0.1 release without using `all` I would suggest we do that for this release and avoid having to remember to back these changes out and accidentally failing to ship the excluded platforms next time round.

**Comment by sophia-guo** [comment]
Yes, we can complete the release without using all. However this change actually should be part of https://github.com/adoptium/installer/pull/757/files.

**Comment by karianna** [comment]
@sophia-guo Do you want to close this PR then?

**Pull request closed without merging**
