### PR TITLE
Do not fail jenkins if test fails so rpm can be archived

### LINKED ISSUE #362: Make sure archive rpm generated even if the testcontainer tests failed.
Current testcontainer tests don't work with ppc64le and s390x architecture we'd like to update to make sure those ppc64le and s390x rpm will be archived and released even if the tests fail.

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #362 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Originally works no rpm be archived due to the test failures. https://ci.adoptopenjdk.net/view/work-in-progress/job/adoptium-packages-linux-pipeline/51/

Now: https://ci.adoptopenjdk.net/view/work-in-progress/job/adoptium-packages-linux-pipeline/53/

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
I'm not sure about this change, can we not skip the tests for other platforms (like we do with aarch64 in the setup stage)

**Comment by smlambert** [comment]
I'd advised that we do something temporarily while we work out the testing for other platforms (an issue for fixing https://github.com/adoptium/installer/issues/375).  Skipping tests if its easy/doable is likely a better approach  as a temporary state.

**Comment by sxa** [comment]
I think there's also an issue with the tests being somewhat flakey. I've seen that in some of the runs I'm doing. One time they'll work, the next time they won't. When I've looked at them they've generally been the ones for the Red Hat rpms, but not necessarily the same one on each run, so this bypasses that problem for now, but we do need to make sure later that we're not "hiding" any real problems with this.

**Pull request merged**
