### PR TITLE
Fix provided packages list for Temurin RPM packages

### LINKED ISSUE #415: Temurin RPM packages do not provide `java-headless` package
If some RPM package (`mysql-connector-java` for example) depends on `java-headless` package then it's impossible to satisfy such dependency with Temurin RPM packages because they provide only `java`, but not `java-headless`.

### PR DESCRIPTION
**Pull request by medb**
Examples of what packages default Java RPMs provide:
- https://centos.pkgs.org/8/centos-appstream-aarch64/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.aarch64.rpm.html
- https://centos.pkgs.org/8/centos-appstream-aarch64/java-1.8.0-openjdk-devel-1.8.0.312.b07-2.el8_5.aarch64.rpm.html
- https://centos.pkgs.org/8/centos-appstream-aarch64/java-1.8.0-openjdk-headless-1.8.0.312.b07-2.el8_5.aarch64.rpm.html

Fixes #415

### CODE REVIEW

**Comment by karianna** [comment]
@medb - Thanks for your contribution.  Are you able to sign the Eclipse CLA?

See https://www.eclipse.org/legal/ECA.php and the relevant section:

_To complete and submit a ECA, log into the [https://www.eclipse.org/contribute/cla](Eclipse projects forge) (you will need to create an account with the Eclipse Foundation if you have not already done so); click on "Eclipse Contributor Agreement"; and Complete the form. Be sure to use the same email address when you register for the account that you intend to use when you commit to Git._

**Review by karianna — COMMENTED** [review]
Assuming `1.8.0` is correct over `8` then I'm good with this.

**Comment by medb** [comment]
@karianna signed Eclipse CLA

Yes, I checked RHEL packages itself - they refer to Java version as 1.8.0, not 8:

```
$ sudo rpm -qv --provides java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64.rpm
auto: application()
auto: application(java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64-policytool.desktop)
manual: java = 1:1.8.0
manual: java-1.8.0 = 1:1.8.0.312.b07-2.el8_5
manual: java-1.8.0-openjdk = 1:1.8.0.312.b07-2.el8_5
manual: java-1.8.0-openjdk(x86-64) = 1:1.8.0.312.b07-2.el8_5
manual: java-openjdk = 1:1.8.0.312.b07-2.el8_5
manual: jre = 1.8.0
manual: jre-1.8.0 = 1:1.8.0.312.b07-2.el8_5
manual: jre-1.8.0-openjdk = 1:1.8.0.312.b07-2.el8_5
manual: jre-openjdk = 1:1.8.0.312.b07-2.el8_5
auto: libjawt.so()(64bit)
auto: libjawt.so(SUNWprivate_1.1)(64bit)

$ sudo rpm -qv --provides java-1.8.0-openjdk-devel-1.8.0.312.b07-2.el8_5.x86_64.rpm
auto: application()
auto: application(java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64-jconsole.desktop)
manual: java-1.8.0-devel = 1:1.8.0.312.b07
manual: java-1.8.0-openjdk-devel = 1:1.8.0.312.b07
manual: java-1.8.0-openjdk-devel = 1:1.8.0.312.b07-2.el8_5
manual: java-1.8.0-openjdk-devel(x86-64) = 1:1.8.0.312.b07-2.el8_5
manual: java-devel = 1:1.8.0
manual: java-devel-openjdk = 1:1.8.0.312.b07
manual: java-sdk = 1:1.8.0
manual: java-sdk-1.8.0 = 1:1.8.0.312.b07
manual: java-sdk-1.8.0-openjdk = 1:1.8.0.312.b07
manual: java-sdk-openjdk = 1:1.8.0.312.b07
auto: libjawt.so()(64bit)
auto: libjawt.so(SUNWprivate_1.1)(64bit)

$ sudo rpm -qv --provides java-1.8.0-openjdk-headless-1.8.0.312.b07-2.el8_5.x86_64.rpm
manual: /usr/bin/jjs
config: config(java-1.8.0-openjdk-headless) = 1:1.8.0.312.b07-2.el8_5
manual: java-1.8.0-headless = 1:1.8.0.312.b07-2.el8_5
manual: java-1.8.0-openjdk-headless = 1:1.8.0.312.b07-2.el8_5
manual: java-1.8.0-openjdk-headless(x86-64) = 1:1.8.0.312.b07-2.el8_5
manual: java-headless = 1:1.8.0
manual: java-openjdk-headless = 1:1.8.0.312.b07-2.el8_5
manual: jre-1.8.0-headless = 1:1.8.0.312.b07-2.el8_5
manual: jre-1.8.0-openjdk-headless = 1:1.8.0.312.b07-2.el8_5
manual: jre-headless = 1:1.8.0
manual: jre-openjdk-headless = 1:1.8.0.312.b07-2.el8_5
auto: libjava.so()(64bit)
auto: libjava.so(SUNWprivate_1.1)(64bit)
auto: libjsig.so()(64bit)
auto: libjvm.so()(64bit)
auto: libjvm.so(SUNWprivate_1.1)(64bit)
auto: libverify.so()(64bit)
auto: libverify.so(SUNWprivate_1.1)(64bit)
```

**Review by gdams — APPROVED** [review]

**Comment by gdams** [comment]
I assume we likely need to update the suse Provides too? https://GitHub.com/adoptium/installer/linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

**Review by karianna — APPROVED** [review]
LGTM

**Comment by medb** [comment]
Updated OpenSUSE Temurin packages too, @gdams PTAL.

**Review by gdams — APPROVED** [review]

**Pull request merged**
