### PR TITLE
linux: remove unnecessary update commands

### PR DESCRIPTION
**Pull request by gdams**
the yum/dnf update commands take a long time and slow down the CI unnecessarily.

### CODE REVIEW

**Review by karianna — COMMENTED** [review]
Can we replace with something more lightweight as opposed to removing entirely?

**Comment by gdams** [comment]
> Can we replace with something more lightweight as opposed to removing entirely?

It's simply not required for the test, there is no need for us to verify that dnf/yum update works on a Linux distro (it's safe to say that any problems with that would be a problem for the upstream distro to resolve)

**Review by karianna — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
Testing codefreeze

**Comment by gdams** [comment]
Good bot

**Comment by gdams** [comment]
Going to request merge exception for this PR as it will significantly speed up the Linux installer release process. Risk is very low.

**Review by smlambert — APPROVED** [review]

**Pull request merged**
